theme: minima
title: Movimento 5 Stelle
description: sito open source con tutti i contatti base per il Movimento 5 Stelle 2050
show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
